# -*- coding: utf-8 -*-
"""NOK_Estruturas de Decisão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlRbxmIaYC5SGqqQcvMGgsqd3e_xJ4zA

# Estruturas de decisão

<span style="color: red;"><b>Todos os exercícios são feitos partindo-se do pressuposto de que todas as entradas são dadas de forma correta. Casos limite não mencionados no enunciado não são abordados porque não fazem parte do exercício.</b></span>

#### 1. Faça um Programa que peça dois números e imprima o maior deles.
"""

numero_1 = int(input("Digite um número:"))
numero_2 = int(input("Digite o segundo número:"))
if numero_1 > numero_2:
  print('O maior número é o {}'.format(numero_1))
else:
  print('O maior número é o: {}'.format(numero_2))

"""#### 2. Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo."""

pos_or_neg = int(input("Digite um número:"))
if pos_or_neg < 0:
  print('O {} é um número negativo' .format(pos_or_neg))
elif pos_or_neg == 0:
  print('O {} não é positivo nem negativo. Digite um valor válido' .format(pos_or_neg))
else:
  print('O {} é um número positivo' .format(pos_or_neg))

"""#### 3. Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido."""

letra = input("Digite F ou M:")
if letra == "F" or letra == "f":
  print("Feminino")
elif letra == "M" or letra == "m":
  print("Masculino")
else:
  print("Sexo inválido")

"""#### 4. Faça um Programa que verifique se uma letra digitada é vogal ou consoante.

"""

letras =input("Digite uma letra qualquer: ")
vogais = 'aeiou'
for vogal in vogais:
  if letras == vogal or letras == vogal.upper():
    print("Vogal")
    break
  else:
    print("Consoante")
    break

"""### 5. Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:
<p> A mensagem "Aprovado", se a média alcançada for maior ou igual a sete </p><p> A mensagem "Reprovado", se a média for menor do que sete;</p><p> A mensagem "Aprovado com Distinção", se a média for igual a dez.</p>
"""

from statistics import median
nota1 = int(input("digite a 1ª nota: "))
nota2 = int(input("digite a 2ª nota: "))
mean = median([nota1,nota2])
if mean < 7:
  print('"Reprovado"')
elif mean == 10:
  print('"Aprovado com Distinção"')
else:
  print('"Aprovado"')

"""### 6. Faça um Programa que leia três números e mostre o maior deles."""

number1 = int(input('Digite o 1º número '))
number2 = int(input('Digite o 2ª número '))
number3 = int(input('Digite o 3ª número '))
listnumber = [number1,number2,number3]
print('O maior número é o {} e foi o {}º número digitado'.format(max(listnumber), listnumber.index(max(listnumber))+1))

"""### 7. Faça um Programa que leia três números e mostre o maior e o menor deles."""

number_one = int(input('Digite o 1º número '))
number_two = int(input('Digite o 2ª número '))
number_three = int(input('Digite o 3ª número '))
listnumber = [number_one,number_two,number_three]
print('O maior número é o {} e o menor é o {}'.format(max(listnumber), min(listnumber)))

"""### 8. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

preco1 = float(input())
preco2 = float(input())
preco3 = float(input())
listcost =[preco1,preco2,preco3]
print('O produto que você deve comprar é o {}'.format(min(listcost)))

"""### 9. Faça um Programa que leia três números e mostre-os em ordem decrescente."""

first = float(input())
second = float(input())
third = float(input())
listnumeros = [first,second,third]
listnumeros.sort(reverse=True)
print(listnumeros)

"""### 10. Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso."""

print('Qual turno você estuda? Digite M para matutino, V para vespertino e N para noturno')
turno = input()
if turno.upper() == 'M':
  print('Bom dia!')
elif turno.upper() == 'V':
  print('Boa tarde!')
elif turno.upper() == 'N':
  print('Boa Noite!')
else:
  print('Valor inválido!')

"""#### 11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:

> ##### salários até R\$ 280,00 (incluindo) : aumento de 20%
> ##### salários entre R\$ 280,00 e R\$ 700,00 : aumento de 15%
> ##### salários entre R\$ 700,00 e R\$ 1500,00 : aumento de 10%
> ##### salários de R\$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:
> ###### o salário antes do reajuste;
> ###### o percentual de aumento aplicado;
> ###### o valor do aumento;
> ###### o novo salário, após o aumento.
> ###### Obs: Não vamos nos preocupar tanto com a formatação dos números (nº de casas decimais, por exemplo, veremos isso no próximo módulo)
"""
salario = float(input())
if salario < 280:
  reajuste = 20
  newsalario = salario*(1+(reajuste/100))
  print('O salário antes do reajuste é de R${:.2f}'.format(salario))
  print('O reajuste foi de {}%'.format(reajuste))
  print('O aumento foi de R${:.2f}'.format(salario*((reajuste/100))))
  print('O novo salário é R${:.2f}'.format(newsalario))
elif salario >= 280 and salario <700:
  reajuste = 15
  newsalario = salario*(1+(reajuste/100))
  print('O salário antes do reajuste é de R${:.2f}'.format(salario))
  print('O reajuste foi de {}%'.format(reajuste))
  print('O aumento foi de R${:.2f}'.format(salario*((reajuste/100))))
  print('O novo salário é R${:.2f}'.format(newsalario))
elif salario >= 700 and salario <1500:
  reajuste = 10
  newsalario = salario*(1+(reajuste/100))
  print('O salário antes do reajuste é de R${:.2f}'.format(salario))
  print('O reajuste foi de {}%'.format(reajuste))
  print('O aumento foi de R${:.2f}'.format(salario*((reajuste/100))))
  print('O novo salário é R${:.2f}'.format(newsalario))
else:
  reajuste = 5
  newsalario = salario*(1+(reajuste/100))
  print('O salário antes do reajuste é de R${:.2f}'.format(salario))
  print('O reajuste foi de {}%'.format(reajuste))
  print('O aumento foi de R${:.2f}'.format(salario*((reajuste/100))))
  print('O novo salário é R${:.2f}'.format(newsalario))


"""#### 12 . Faça um programa para o cálculo de uma folha de pagamento, sabendo que os descontos são do Imposto de Renda, que depende do salário bruto (conforme tabela abaixo) e 3% para o Sindicato e que o FGTS corresponde a 11% do Salário Bruto, mas não é descontado (é a empresa que deposita). O Salário Líquido corresponde ao Salário Bruto menos os descontos. O programa deverá pedir ao usuário o valor da sua hora e a quantidade de horas trabalhadas no mês.

Desconto do IR:<br>
Salário Bruto até 900 (inclusive) - isento<br>
Salário Bruto até 1500 (inclusive) - desconto de 5%<br>
Salário Bruto até 2500 (inclusive) - desconto de 10%<br>
Salário Bruto acima de 2500 - desconto de 20%<br>
Imprima na tela as informações, dispostas conforme o exemplo abaixo. No exemplo o valor da hora é 5 e a quantidade de hora é 220.

Salário Bruto: (5 * 220)        : R\\$ 1100,00<br>
(-) IR (5%)                     : R\\$   55,00<br>
(-) INSS ( 10%)                 : R\\$  110,00<br>
FGTS (11%)                      : R\\$  121,00<br>
Total de descontos              : R\\$  165,00<br>
Salário Liquido                 : R\\$  935,00<br>

###### Obs: Não vamos nos preocupar tanto com a formatação dos números (nº de casas decimais, por exemplo, veremos isso no próximo módulo)
"""

valor_hr = float(input())
salario2 = 220*valor_hr
inss = 0.1
if salario2 <= 900:
  ir = 1
  print('Salário bruto: R$ {:.2f}'.format(salario2))
  print('Isento de IR')
  print('(-) INSS({:.1%}): R$ {:.2f}'.format(inss,salario2*inss))
  print('FGTS (11%): R$ {:.2f}'.format(salario2*(11/100)))
  print('Total de descontos: R$ {:.2f}'.format(salario2*(11/100)))
  print('Salário Liquido: R$ {:.2f}'.format(salario2-salario2*(11/100)))
elif salario2 > 900 and salario2 <= 1500:
  ir = 0.05
  print('Salário bruto: R$ {:.2f}'.format(salario2))
  print('(-) IR({:.1%}): R$ {:.2f}'.format(ir,salario2*ir))
  print('(-) INSS({:.1%}): R$ {:.2f}'.format(inss,salario2*inss))
  print('FGTS (11%): R$ {:.2f}'.format(salario2*(11/100)))
  print('Total de descontos: R$ {:.2f}'.format(salario2*(10/100)+(salario2*ir)))
  print('Salário Liquido: R$ {:.2f}'.format(salario2-(salario2*(10/100)+(salario2*ir))))
elif salario2 > 1500 and salario2 <= 2500:
  ir = 0.1
  print('Salário bruto: R$ {:.2f}'.format(salario2))
  print('(-) IR({:.1%}): R$ {:.2f}'.format(ir,salario2*ir))
  print('(-) INSS({:.1%}): R$ {:.2f}'.format(inss,salario2*inss))
  print('FGTS (11%): R$ {:.2f}'.format(salario2*(11/100)))
  print('Total de descontos: R$ {}'.format(salario2*(10/100)+(salario2*ir)))
  print('Salário Liquido: R$ {}'.format(salario2-(salario2*(10/100)+(salario2*ir))))
else:
  ir = 0.2
  print('Salário bruto: R$ {:.2f}'.format(salario2))
  print('(-) IR({:.1%}): R$ {:.2f}'.format(ir,salario2*ir))
  print('(-) INSS({:.1%}): R$ {:.2f}'.format(inss,salario2*inss))
  print('FGTS (11%): R$ {:.2f}'.format(salario2*(11/100)))
  print('Total de descontos: R$ {}'.format(salario2*(10/100)+(salario2*ir)))
  print('Salário Liquido: R$ {}'.format(salario2-(salario2*(10/100)+(salario2*ir))))

"""#### 13. Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido."""
dia = input()
semana ='1234567'
if dia in semana:
  if dia == '1':
    print('Domingo')
  elif dia == '2':
    print('Segunda')
  elif dia == '3':
    print('Terça')
  elif dia == '4':
    print('Quarta')
  elif dia == '5':
    print('Quinta')
  elif dia == '6':
    print('Sexta')
  elif dia == '7':
    print('Sábado')
else:
  print('Digite um número válido (1 a 7)')


"""#### 14. Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a sua média. Em seguida, mostre qual conceito o aluno teve. A atribuição de conceitos obedece à tabela abaixo:
<pre>
Média de Aproveitamento  Conceito
Entre 9.0 e 10.0        A
Entre 7.5 e 9.0         B
Entre 6.0 e 7.5         C
Entre 4.0 e 6.0         D
Entre 4.0 e zero        E
</pre>
"""

nota01 = float(input())
nota02 = float(input())
media_1 = (nota01+nota02)/2
print('Média: ',media_1)
if media_1 < 4.0:
  print('Conceito E')
elif media_1 >= 4.0 and media_1 < 6.0:
  print('Conceito D')
elif media_1 >= 6.0 and media_1 < 7.5:
  print('Conceito C')
elif media_1 >= 7.5 and media_1 < 9.0:
  print('Conceito B')
else:
  print('Conceito A')

"""####15. Faça um Programa que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
####Dicas:
####Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
Triângulo Equilátero: três lados iguais;
Triângulo Isósceles: quaisquer dois lados iguais;
Triângulo Escaleno: três lados diferentes;
"""



"""####16. Faça um programa que calcule as raízes de uma equação do segundo grau, na forma ax2 + bx + c. O programa deverá pedir os valores de a, b e c e fazer as consistências, informando ao usuário nas seguintes situações:
####Se o usuário informar o valor de A igual a zero, a equação não é do segundo grau e o programa não deve fazer pedir os demais valores, sendo encerrado;
####Se o delta calculado for negativo, a equação não possui raizes reais. Informe ao usuário e encerre o programa;
####Se o delta calculado for igual a zero a equação possui apenas uma raiz real; informe-a ao usuário;
####Se o delta for positivo, a equação possui duas raiz reais; informe-as ao usuário;

#### 17. Você está construindo um calendário para controlar dias de trabalho a pedido do RH. Nessa construção, você vai precisar definir quais anos são bissextos e quais não são, para montar o calendário de forma correta. Faça um Programa que peça um número correspondente a um determinado ano e em seguida informe se este ano é ou não bissexto.

Dica para determinar se um ano é bissexto:
- São bissextos todos os anos múltiplos de 400, p.ex.: 1600, 2000, 2400, 2800...
- São bissextos todos os múltiplos de 4, exceto se for múltiplo de 100 mas não de 400,
p.ex.: 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028...
- Não são bissextos todos os demais anos.<br>
ex1: 2004 é múltiplo de 4, mas não é múltiplo de 100, então é bissexto.
ex2: 2000 é múltiplo de 4, mas é múltiplo de 100, só que também é multiplo de 400, então é bissexto (porque todo ano múltiplo de 400 é bissexto, independente do resto).
ex3: 1900 é múltiplo de 4, é múltiplo de 100, mas não é múltiplo de 400, então não é bissexto



Dica: lembre que: numero % 4 é o resto da divisão do número por 4, ex: 10 % 3 = 1 (já que 10/3 = 3 e resta 1)
"""

ano = int(input())
if ano%4 == 0 and ano%100 == 0 and ano%400 != 0:
  print('Não é ano bissexto')
elif ano%4 == 0 and ano%100 == 0 and ano%400 == 0:
  print('É ano bissexto')
elif ano%4 == 0 and ano%100 != 0:
  print('É ano bissexto')
elif ano%4 != 0:
  print('Não é ano bissexto')

"""####18. Faça um Programa que peça uma data no formato dd/mm/aaaa e determine se a mesma é uma data válida."""



"""####19. Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
####Observando os termos no plural a colocação do "e", da vírgula entre outros.
####Exemplo:
####326 = 3 centenas, 2 dezenas e 6 unidades
####12 = 1 dezena e 2 unidades
####Testar com: 326, 300, 100, 320, 310,305, 301, 101, 311, 111, 25, 20, 10, 21, 11, 1, 7 e 16
"""



"""#### 20. Faça um Programa para leitura de três notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e presentar:
<pre>
A mensagem "Aprovado", se a média for maior ou igual a 7, com a respectiva média alcançada;
A mensagem "Reprovado", se a média for menor do que 7, com a respectiva média alcançada;
A mensagem "Aprovado com Distinção", se a média for igual a 10.
</pre>
"""

nota_um = float(input())
nota_dois = float(input())
nota_tres = float(input())
media_dois = (nota_um+nota_dois+nota_tres)/3
print('Média: {:.2f}'.format(media_dois))
if media_dois < 10.0 and media_dois >= 7:
  print('Aprovado')
elif media_dois == 10:
  print('Aprovado com Distinção')
else:
  print('Reprovado')

"""#### 21. Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.
<pre>
Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;
Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.
</pre>

Dica1: numero // 10 vai te dar como resposta a parte inteira da divisão do número por 10.<br>
Dica2: numero % 10 vai te dar o resto da divisão do número por 10.
"""



"""####22. Faça um Programa que peça um número inteiro e determine se ele é par ou impar. Dica: utilize o operador módulo (resto da divisão)."""



"""####23. Faça um Programa que peça um número e informe se o número é inteiro ou decimal. Dica: utilize uma função de arredondamento."""



"""####24.Faça um Programa que leia 2 números e em seguida pergunte ao usuário qual operação ele deseja realizar. O resultado da operação deve ser acompanhado de uma frase que diga se o número é:
par ou ímpar;
positivo ou negativo;
inteiro ou decimal.
"""



"""#### 25. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
<pre>
"Telefonou para a vítima?"
"Esteve no local do crime?"
"Mora perto da vítima?"
"Devia para a vítima?"
"Já trabalhou com a vítima?"
O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente".
</pre>
"""



"""#### 26. Um posto está vendendo combustíveis com a seguinte tabela de descontos:

Álcool:
até 20 litros, desconto de 3% por litro
acima de 20 litros, desconto de 5% por litro
Gasolina:
até 20 litros, desconto de 4% por litro
acima de 20 litros, desconto de 6% por litro

Escreva um algoritmo que leia o número de litros vendidos, o tipo de combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser pago pelo cliente sabendo-se que o preço do litro da gasolina é R\$ 2,50 o preço do litro do álcool é R\$ 1,90.

"""



"""#### 27. Uma fruteira está vendendo frutas com a seguinte tabela de preços:

|  |                      Até 5 Kg          | Acima de 5 Kg|
|--|--|--|
|Morango     |    R\$ 2,50 por Kg         | R\$ 2,20 por Kg|
|Maçã       |     R\$ 1,80 por Kg        |  R\$ 1,50 por Kg|

Se o cliente comprar mais de 8 Kg em frutas ou o valor total da compra ultrapassar R$ 25,00, receberá ainda um desconto de 10% sobre este total. Escreva um algoritmo para ler a quantidade (em Kg) de morangos e a quantidade (em Kg) de maças adquiridas e escreva o valor a ser pago pelo cliente.

"""

quilos_morango = float(input())
quilos_maca = float(input())
if quilos_morango < 5:
  preco_mor = quilos_morango*2.5
  print('O preço total dos morangos é de R${:.2f}'.format(preco_mor))
else:
  preco_mor = quilos_morango*2.2
  print('O preço total dos morangos é de R${:.2f}'.format(preco_mor))
if quilos_maca < 5:
  preco_maca = quilos_morango*1.8
  print('O preço total das maças é de R${:.2f}'.format(preco_maca))
else:
  preco_maca = quilos_morango*1.5
  print('O preço total das maças é de R${:.2f}'.format(preco_maca))



"""#### 28. O Hipermercado Tabajara está com uma promoção de carnes que é imperdível. Confira:

|                 | Até 5 Kg |          Acima de 5 Kg|
|--------|-------- |-------|
|File Duplo     | R\$ 4,90 por Kg        |  R\$ 5,80 por Kg|
|Alcatra       |  R\$ 5,90 por Kg      |    R\$ 6,80 por Kg|
|Picanha      |   R\$ 6,90 por Kg       |   R\$ 7,80 por Kg|

Para atender a todos os clientes, cada cliente poderá levar apenas um dos tipos de carne da promoção, porém não há limites para a quantidade de carne por cliente. Se compra for feita no cartão Tabajara o cliente receberá ainda um desconto de 5% sobre o total da compra. Escreva um programa que peça o tipo e a quantidade de carne comprada pelo usuário e gere um cupom fiscal, contendo as informações da compra: tipo e quantidade de carne, preço total, tipo de pagamento, valor do desconto e valor a pagar.

"""



"""#### <b>EXTRA</b>
João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas.
"""

quilos = float(input())
variacao = quilos - 50
if variacao > 0:
  preco = variacao * 4
  print('Nessa pesca houve uma variação de {}Kg, sendo assim deve-se pagar RS{:.2f} de multa'.format(variacao, preco))
else:
  print('Não houve excesso de peso.')
